# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yunzai_nonebot.rpc import hola_pb2 as yunzai__nonebot_dot_rpc_dot_hola__pb2


class PipeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Option = channel.unary_unary(
                '/hola.Pipe/Option',
                request_serializer=yunzai__nonebot_dot_rpc_dot_hola__pb2.OptionCode.SerializeToString,
                response_deserializer=yunzai__nonebot_dot_rpc_dot_hola__pb2.OptionCode.FromString,
                )
        self.Channel = channel.stream_stream(
                '/hola.Pipe/Channel',
                request_serializer=yunzai__nonebot_dot_rpc_dot_hola__pb2.ToServer.SerializeToString,
                response_deserializer=yunzai__nonebot_dot_rpc_dot_hola__pb2.ToClient.FromString,
                )


class PipeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Option(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Channel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Option': grpc.unary_unary_rpc_method_handler(
                    servicer.Option,
                    request_deserializer=yunzai__nonebot_dot_rpc_dot_hola__pb2.OptionCode.FromString,
                    response_serializer=yunzai__nonebot_dot_rpc_dot_hola__pb2.OptionCode.SerializeToString,
            ),
            'Channel': grpc.stream_stream_rpc_method_handler(
                    servicer.Channel,
                    request_deserializer=yunzai__nonebot_dot_rpc_dot_hola__pb2.ToServer.FromString,
                    response_serializer=yunzai__nonebot_dot_rpc_dot_hola__pb2.ToClient.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hola.Pipe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pipe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Option(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hola.Pipe/Option',
            yunzai__nonebot_dot_rpc_dot_hola__pb2.OptionCode.SerializeToString,
            yunzai__nonebot_dot_rpc_dot_hola__pb2.OptionCode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Channel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/hola.Pipe/Channel',
            yunzai__nonebot_dot_rpc_dot_hola__pb2.ToServer.SerializeToString,
            yunzai__nonebot_dot_rpc_dot_hola__pb2.ToClient.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
